In [4]:
import numpy as np

beta = np.array([[0.6, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                 [0, 0, 0.2, 0.4, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0.5, 0.3, 0.2, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.4, 0.5, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0.4, 0.3]])

theta = np.array([[0, 0, 0.5, 0, 0.5],
                  [1, 0, 0, 0, 0],
                  [0, 0, 0.3, 0, 0.7],
                  [0, 1, 0, 0, 0],
                  [0, 0.5, 0, 0.5, 0]])

array([[0. , 0. , 0.5, 0. , 0.5],
       [1. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.3, 0. , 0.7],
       [0. , 1. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0.5, 0. ]])

In [62]:
beta.shape

(5, 14)

In [59]:
sentence = [2, 6, 12, 9, 3, 1, 13]
pi_k = 1/5

In [44]:
def p_forward(t, k, beta, theta):
    if t == 1:
        return beta[k][1] * 1/5
    else:
        sum_forward = 0
        for i in range(len(theta)):
            print(type(p_forward(t - 1, i, beta, theta)), i, t, k)
            sum_forward += p_forward(t - 1, i, beta, theta) * theta[i][k - 1] * beta[k - 1][t]

In [88]:
def forwardprobs(observations, initialprob, trans, emis, numstates):
    print(emis.shape, trans.shape)
    forwardmatrix = np.zeros((numstates, len(observations)))

    # initialization

    obs_index = 0
    
    for s in range(numstates):

        forwardmatrix[ s, 0 ] = initialprob[s] * emis[ s, obs_index]

    # recursion step

    for t in range(1, len(observations)):

        for s in range(numstates):
            #print(t, s)
            forwardmatrix[s, t] = emis[s, t] * sum([forwardmatrix[s2, t-1] * trans[s2, s] \

                                       for s2 in range(numstates)])
            
    return forwardmatrix

In [74]:
a = [i for i in range(14)]
[1/5 for i in range(5)]

[0.2, 0.2, 0.2, 0.2, 0.2]

In [89]:
gg = forwardprobs(a, [1/5 for i in range(5)], theta, beta, 5)

(5, 14) (5, 5)


In [90]:
gg

array([[0.12, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ]])

In [67]:
p_forward = np.zeros(beta.shape)

for i in range(beta.shape[0]):
    p_forward[i][0] = beta[i][0] * pi_k

for i in range(1, beta.shape[1]):
    for j in range(beta.shape[0]):
        sum_k = 0
        for k in range(beta.shape[0]):
            #print(j, i, k)
            sum_k += p_forward[k][i-1] * theta[j][k] * beta[j][i]
        p_forward[j][i] = sum_k

In [68]:
p_forward

array([[0.12, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  ]])

In [ ]:
N = sentence[-1]
proba_sentence = 0
for word in sentence:
    p_forward_word = 0
    for i in range(1, N):
        